# fly.toml app configuration file generated for server-blue-pond-7993 on 2024-08-14T18:35:54+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'assesement-task-2'
primary_region = 'cdg'

[build]
  dockerfile = "DOCKERFILE"
  ignorefile = "dockerignore"
  build-target = "deploy"
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
